name: eros_party_hra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7

  # 📦 QR & skener
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.0

  # 🔥 Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/banka_ukolu.json