name: eros_party_hra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  path: ^1.9.0

  flutter_localizations:
    sdk: flutter

  intl: any

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  
  url_launcher: ^6.3.1

  # 📦 QR & skener
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.0

  # 🔥 Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 🎨 Ikona aplikace
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/icon/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/banka_ukolu.json