// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcszCIXWynJH3yBgyP5SimB56HijUcAGg',
    appId: '1:956940813038:web:242c7232c92a4c833ee9ff',
    messagingSenderId: '956940813038',
    projectId: 'eros-party-game',
    authDomain: 'eros-party-game.firebaseapp.com',
    storageBucket: 'eros-party-game.firebasestorage.app',
    measurementId: 'G-VJV5EXL9EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8jTDbCebmz2AqmKpdVb7m4WPllrGVKqs',
    appId: '1:956940813038:android:4bd128926a99b9203ee9ff',
    messagingSenderId: '956940813038',
    projectId: 'eros-party-game',
    storageBucket: 'eros-party-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjKR2NTmX_QVkYVXJUVnqIsn-w-xKZMw',
    appId: '1:956940813038:ios:f8f34f2b43f8eb533ee9ff',
    messagingSenderId: '956940813038',
    projectId: 'eros-party-game',
    storageBucket: 'eros-party-game.firebasestorage.app',
    iosBundleId: 'com.example.erosPartyHra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApjKR2NTmX_QVkYVXJUVnqIsn-w-xKZMw',
    appId: '1:956940813038:ios:f8f34f2b43f8eb533ee9ff',
    messagingSenderId: '956940813038',
    projectId: 'eros-party-game',
    storageBucket: 'eros-party-game.firebasestorage.app',
    iosBundleId: 'com.example.erosPartyHra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcszCIXWynJH3yBgyP5SimB56HijUcAGg',
    appId: '1:956940813038:web:1e15d0f22559eaba3ee9ff',
    messagingSenderId: '956940813038',
    projectId: 'eros-party-game',
    authDomain: 'eros-party-game.firebaseapp.com',
    storageBucket: 'eros-party-game.firebasestorage.app',
    measurementId: 'G-RKNV23RW61',
  );

}